### PR TITLE
Return promise on server.stop().

### LINKED ISSUE #45: Port stays in use after server.stop()
### Steps to reproduce
Run the following script with any WebThing in `./webthing.js`.
```
const {
  SingleThing,
  WebThingServer,
} = require('webthing');
const WebThing = require('./webthing.js');

async function test() {
  const PORT = 8000;
  const thing = new WebThing();
  const server = new WebThingServer(new SingleThing(thing), PORT);
  console.log('start 1');
  await server.start();
  server.stop();
  console.log('start 2');
  await server.start();
  server.stop();
}

test().catch(console.error);
```

### Actual
The server fails to start after it got stopped, because the port is still in use. Output:
```
start 1
start 2
Error [ERR_SERVER_ALREADY_LISTEN]: Listen method has been called more than once without closing.
    at Server.listen (net.js:1372:11)
    at ipPromise.then (/home/jaller94/Git/webthings/webthing-add/node_modules/webthing/lib/server.js:765:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

### Expected
The server starts and stops two times without a problem.

### PR DESCRIPTION
**Pull request by mrstegeman**
Fixes #45

### CODE REVIEW

**Comment by jaller94** [comment]
Instead of
`.then(() => process.exit()).catch(() => process.exit());`
I would prefer
`.catch(console.warn).finally(() => process.exit());`
in the examples.

File: lib/server.js [hunk 1]
```diff
@@ -771,12 +771,36 @@ class WebThingServer {
...
+          } else {
+            resolve();
+          }
+        });
+      }));
     }
-    this.server.close();
+
+    promises.push(new Promise((resolve, reject) => {
+      this.server.close((error) => {
```
Comment (jaller94) [inline lib/server.js]: This is awesome. 👍
Right, `http` from NodeJS has a callback as well.
https://nodejs.org/api/net.html#net_server_close_callback

**Comment by mrstegeman** [comment]
@jaller94 I intentionally didn't use `.finally()`, as it's not supported until Node v10.
